In [5]:
import os
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# create an empty dataframe
df = pd.DataFrame()

benchmark = 'ood'
method_list = ['msp', 'odin', 'ebo', 'mds', 'gmm1', 'gmm4']

for method in method_list:
    dirname = f'./mnist_0408_3/mnist_lenet_test_ood_{benchmark}_{method}_0408_3'
    filename = os.path.join(dirname, 'ood.csv')
    sub_df = pd.read_csv(filename)
    sub_df['method'] = method
    df = df.append(sub_df)

data = []
dataset_list = list(df['dataset'][:8])
for dataset in dataset_list:
    df_sub_dataset = df[df['dataset'] == dataset]
    metric_list = [dataset]
    metric_list.extend(list(df_sub_dataset['FPR@95']))
    metric_list.extend(list(df_sub_dataset['AUROC']))
    metric_list.extend(list(df_sub_dataset['AUPR_IN']))
    data.append(metric_list)

header = ['dataset'] + \
['fpr_'+method for method in method_list] + \
['auroc_'+method for method in method_list] + \
['aupr_'+method for method in method_list]
df_report = pd.DataFrame(data, columns=header)

df_report

,dataset,fpr_msp,fpr_odin,fpr_ebo,fpr_mds,fpr_gmm1,fpr_gmm4,auroc_msp,auroc_odin,auroc_ebo,auroc_mds,auroc_gmm1,auroc_gmm4,aupr_msp,aupr_odin,aupr_ebo,aupr_mds,aupr_gmm1,aupr_gmm4
0,notmnist,43.09,37.70,44.06,1.77,2.64,0.78,88.77,89.85,88.44,99.67,99.50,99.79,75.72,77.83,75.97,99.36,99.09,99.57
1,fashionmnist,24.36,12.95,13.37,5.79,26.20,0.61,94.62,96.55,96.95,98.88,95.86,99.80,93.72,95.86,96.34,98.85,96.28,99.79
2,nearood,33.73,25.33,28.71,3.78,14.42,0.69,91.69,93.20,92.69,99.28,97.68,99.80,84.72,86.84,86.15,99.10,97.68,99.68
3,texture,2.54,1.08,1.05,0.27,40.09,0.00,99.44,99.70,99.72,99.90,95.02,99.94,99.64,99.77,99.76,99.94,97.63,99.97
4,cifar10,7.05,3.06,3.18,0.18,54.43,0.00,98.68,99.31,99.30,99.88,94.19,99.97,98.72,99.27,99.12,99.88,95.86,99.97
5,tin,6.28,2.93,3.13,0.55,59.52,0.00,98.78,99.36,99.37,99.79,93.70,99.96,98.78,99.33,99.25,99.79,95.54,99.96
6,places365,9.92,4.59,4.12,0.45,58.07,0.00,98.19,99.06,99.17,99.81,93.82,99.96,94.87,97.01,96.84,99.42,91.32,99.88
7,farood,6.45,2.92,2.87,0.36,53.03,0.00,98.77,99.36,99.39,99.84,94.18,99.96,98.00,98.84,98.74,99.76,95.09,99.94

In [7]:
for line_array in data:
    values = ['{:.2f}'.format(line_array[i]) for i in range(1, len(line_array))]
    print_line = line_array[0] + '\n'
    for i, element in enumerate(values):
        if i % 6 == 5:
            print_line = print_line + "& \\textbf{" + element + "} \n"
            if i == 17:
                print_line = print_line[:-2] + " \\" + "\\"
        else:
            print_line = print_line + "& " + element
    print(print_line)

notmnist
& 43.09& 37.70& 44.06& 1.77& 2.64& \textbf{0.78}
& 88.77& 89.85& 88.44& 99.67& 99.50& \textbf{99.79}
& 75.72& 77.83& 75.97& 99.36& 99.09& \textbf{99.57} \\
fashionmnist
& 24.36& 12.95& 13.37& 5.79& 26.20& \textbf{0.61}
& 94.62& 96.55& 96.95& 98.88& 95.86& \textbf{99.80}
& 93.72& 95.86& 96.34& 98.85& 96.28& \textbf{99.79} \\
nearood
& 33.73& 25.33& 28.71& 3.78& 14.42& \textbf{0.69}
& 91.69& 93.20& 92.69& 99.28& 97.68& \textbf{99.80}
& 84.72& 86.84& 86.15& 99.10& 97.68& \textbf{99.68} \\
texture
& 2.54& 1.08& 1.05& 0.27& 40.09& \textbf{0.00}
& 99.44& 99.70& 99.72& 99.90& 95.02& \textbf{99.94}
& 99.64& 99.77& 99.76& 99.94& 97.63& \textbf{99.97} \\
cifar10
& 7.05& 3.06& 3.18& 0.18& 54.43& \textbf{0.00}
& 98.68& 99.31& 99.30& 99.88& 94.19& \textbf{99.97}
& 98.72& 99.27& 99.12& 99.88& 95.86& \textbf{99.97} \\
tin
& 6.28& 2.93& 3.13& 0.55& 59.52& \textbf{0.00}
& 98.78& 99.36& 99.37& 99.79& 93.70& \textbf{99.96}
& 98.78& 99.33& 99.25& 99.79& 95.54& \textbf{99.96} \\
places365
& 9.92& 4.59& 4.12& 0.45& 58.07& \textbf{0.00}
& 98.19& 99.06& 99.17& 99.81& 93.82& \textbf{99.96}
& 94.87& 97.01& 96.84& 99.42& 91.32& \textbf{99.88} \\
farood
& 6.45& 2.92& 2.87& 0.36& 53.03& \textbf{0.00}
& 98.77& 99.36& 99.39& 99.84& 94.18& \textbf{99.96}
& 98.00& 98.84& 98.74& 99.76& 95.09& \textbf{99.94} \\